version: "3.8"

services: 
  server:
    volumes: 
      - .:/home/app
      - nodemodules_server:/home/app/node_modules
    ports: 
      - ${PORT}:${PORT}
    command: yarn dev

volumes: 
  nodemodules_server: {}